ARG NAMESPACE=mubox
ARG TAG=latest
FROM ${NAMESPACE}/build:${TAG}

# TODO: Find something for this image to have that the build image doesn't. Nanobox installed ZSH here, but I'm not certain we really want that.
